name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Semantic of the update version"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write # required for push, tag and release

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          # all history is needed to generate the CHANGELOG.md
          fetch-depth: 0

      - name: Install moon
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: false

      - name: Setup toolchains
        run: moon setup

      - name: Bump version
        env:
          VERSION_BUMP: ${{ inputs.bump }}
        run: moon run :bump-version

      - name: Read version
        id: version
        run: |
          VERSION=$(node -p "require('./app/package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT

      - name: Update CHANGELOG.md
        id: git-cliff-changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: .github/cliff-changelog.toml
          args: --tag ${{ steps.version.outputs.tag }} --github-repo ${{ github.repository }} --output CHANGELOG.md

      - name: Update SECURITY.md
        run: |
          MAJOR_MINOR=$(echo "${{ steps.version.outputs.version }}" | cut -d. -f1,2)
          sed -i "s/[0-9]\+\.[0-9]\+\./${MAJOR_MINOR}./g" SECURITY.md

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          if git diff --quiet; then
            echo "‚ùå No changes to commit"
            exit 1
          fi

          git add .
          git commit -m "chore(release): ${{ steps.version.outputs.tag }}"

      - name: Create tag
        run: git tag "${{ steps.version.outputs.tag }}"

      - name: Generate release notes
        id: git-cliff-release-notes
        uses: orhun/git-cliff-action@v4
        with:
          config: .github/cliff-release-notes.toml
          args: --latest --strip all

      - name: Push commit and tag
        run: |
          git push origin main
          git push origin --tags

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.version.outputs.tag }}" \
            --title "Release ${{ steps.version.outputs.tag }}" \
            --notes "${{ steps.git-cliff-release-notes.outputs.content }}" \
            --latest
